---
- name: Join kubernetes cluster
  command: kubeadm join --discovery-token-unsafe-skip-ca-verification --token={{ join_token }} {{ join_addr }}:6443
  register: out
  changed_when: "out.rc == 0 and '/etc/kubernetes/bootstrap-kubelet.conf already exists' not in out.stderr"
  failed_when: "out.rc != 0 and '/etc/kubernetes/bootstrap-kubelet.conf already exists' not in out.stderr"
  become: true

- name: Set kublet node ip
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: 'ExecStart=\/usr\/bin\/kubelet\ \$KUBELET_KUBECONFIG_ARGS'
    replace: 'ExecStart=/usr/bin/kubelet --node-ip={{ kube_ip }} $KUBELET_KUBECONFIG_ARGS'
    backup: yes
  register: kubeletip
  become: true

- name: Force systemd to reread configs
  command: systemctl daemon-reload
  become: true
  when: kubeletip.changed

- name: Restart kubelet service
  command: service kubelet restart 
  become: true
  when: kubeletip.changed

